### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by Jannik44** [rejuce/LikeTaskManager#2]
dude when i download the .zip there is only a mess with files, in the instructions it it saying "download from release tab", but what do you mean with "release tab"??? also there is no official download website where i can download 1(!!) file

**Comment by rejuce** [comment]
you only need to download .zip in case you want to compile it your own

you find the relase section here, like on any other github repository 
![grafik](https://user-images.githubusercontent.com/28755821/112306022-a2908100-8c9f-11eb-9662-34378f611d54.png)

then take the latest release
![grafik](https://user-images.githubusercontent.com/28755821/112306149-c9e74e00-8c9f-11eb-856d-50dfc81ddd13.png)

dont forget to grant executeable permission after download
